export const DEFAULT_GUARDED_DURATION = 1;
export const DEFAULT_JUICE_DURATION = 2;
export const DEFAULT_NON_TARGETABLE_DURATION = 1;
export const DEFAULT_OIL_DURATION = 5;
export const DEFAULT_PARALYSIS_DURATION = 3;
export const DEFAULT_POISON_DURATION = 5;
